# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [8]:
# Create a 1-dimensional NumPy array using np.array()
a1=np.array([1,2,3])

# Create a 2-dimensional NumPy array using np.array()
a2=np.array([[1,2,3],[4,5,6]])

# Create a 3-dimensional Numpy array using np.array()
a3=np.array([[1,2,3],[4,5,6],[7,8,9]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [10]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape, a1.ndim,a1.size,a1.dtype

((3,), 1, 3, dtype('int64'))

In [11]:
# Attributes of 2-dimensional array
a2.shape,a2.ndim,a2.size,a2.dtype

((2, 3), 2, 6, dtype('int64'))

In [12]:
# Attributes of 3-dimensional array
a3.shape,a3.ndim,a3.size,a3.dtype

((3, 3), 2, 9, dtype('int64'))

In [6]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created


In [14]:
# Create an array of shape (10, 2) with only ones
ones=np.ones((10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [16]:
# Create an array of shape (7, 2, 3) of only zeros
arr=np.zeros((7,2,3))
arr

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [20]:
# Create an array within a range of 0 and 100 with step 3
rand=np.arange(0,100)
rand

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [23]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
rand1=np.random.randint(0,11 , size=(7,2))
rand1

array([[ 8,  9],
       [ 2,  6],
       [ 7,  2],
       [ 0,  4],
       [10,  6],
       [10,  0],
       [ 0,  7]], dtype=int32)

In [25]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
rand2=np.random.random((3,5))
rand2

array([[0.20893303, 0.73297955, 0.52416245, 0.30994395, 0.32328446],
       [0.43685635, 0.24352978, 0.11826888, 0.44124496, 0.80742951],
       [0.90810221, 0.66611077, 0.06782347, 0.73633376, 0.15911209]])

In [30]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
rand3=np.random.randint(0,11 , size=(4,6))
rand3

array([[ 6,  3, 10,  7,  4,  6],
       [ 9,  2,  6, 10, 10,  7],
       [ 4,  3,  7,  7,  2,  5],
       [ 4,  1,  7,  5,  1,  4]], dtype=int32)

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [33]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable

rand4=np.random.randint(1,10,size=(3,7))
rand4
# Find the unique numbers in the array you just created
np.unique(rand4)

array([1, 2, 3, 5, 7, 8, 9], dtype=int32)

In [35]:
rand4

array([[8, 5, 2, 5, 8, 9, 9],
       [1, 9, 7, 9, 8, 1, 8],
       [8, 3, 1, 8, 3, 3, 1]], dtype=int32)

In [38]:
# Find the 0'th index of the latest array you created
rand4[0][0]

np.int32(8)

In [41]:
# Get the first 2 rows of latest array you created
rand4[:2]

array([[8, 5, 2, 5, 8, 9, 9],
       [1, 9, 7, 9, 8, 1, 8]], dtype=int32)

In [49]:
# Get the first 2 values of the first 2 rows of the latest array
rand4[:2,:2]

array([[8, 5],
       [1, 9]], dtype=int32)

In [56]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
rand5=np.random.randint(1,11, size=(3,5))
rand6=np.ones((3,5))

In [61]:
# Add the two arrays together
rand7=sum(rand5,rand6)

In [62]:
# Create another array of ones of shape (5, 3)
rand8=np.ones((5,3))

In [66]:
# Try add the array of ones and the other most recent array together
rand9=sum(rand7,rand8.T)
rand9

array([[58., 70., 58., 40., 61.],
       [58., 70., 58., 40., 61.],
       [58., 70., 58., 40., 61.]])

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [67]:
# Create another array of ones of shape (3, 5)
rand10=np.ones((3,5))

In [70]:
# Subtract the new array of ones from the other most recent array
np.subtract(rand10,rand9)

array([[-57., -69., -57., -39., -60.],
       [-57., -69., -57., -39., -60.],
       [-57., -69., -57., -39., -60.]])

In [73]:
# Multiply the ones array with the latest array
rand8*rand10.T

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [75]:
# Take the latest array to the power of 2 using '**'
rand10**2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [76]:
# Do the same thing with np.square()
np.square(rand7)

array([[361., 529., 361., 169., 400.],
       [361., 529., 361., 169., 400.],
       [361., 529., 361., 169., 400.]])

In [77]:
# Find the mean of the latest array using np.mean()
np.mean(rand7)

np.float64(18.8)

In [78]:
# Find the maximum of the latest array using np.max()
np.max(rand7)

np.float64(23.0)

In [79]:
# Find the minimum of the latest array using np.min()
np.min(rand7)

np.float64(13.0)

In [81]:
# Find the standard deviation of the latest array
np.std(rand7)

np.float64(3.249615361854384)

In [82]:
# Find the variance of the latest array
np.var(rand7)

np.float64(10.56)

In [84]:
rand7

array([[19., 23., 19., 13., 20.],
       [19., 23., 19., 13., 20.],
       [19., 23., 19., 13., 20.]])

In [86]:
# Reshape the latest array to (3, 5, 1)
rand11=rand7.reshape(3,5,1)

In [87]:
# Transpose the latest array
rand11.T

array([[[19., 19., 19.],
        [23., 23., 23.],
        [19., 19., 19.],
        [13., 13., 13.],
        [20., 20., 20.]]])

What does the transpose do?

In [88]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
rand12=np.random.randint(0,11,size=(3,3))
rand13=np.random.randint(0,11,size=(3,2))

In [90]:
# Perform a dot product on the two newest arrays you created
rand14=np.dot(rand12,rand13)
rand14

array([[41, 12],
       [40, 24],
       [ 7,  7]], dtype=int32)

In [91]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
#-----------------it wont work

In [92]:
# Perform a dot product on the two newest arrays you created
#------------------it wont work

It doesn't work. How would you fix it?

In [37]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
#--------It happens

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [97]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
#-----------ok
r1=np.random.randint(0,11,size=(3,3))
r2=np.random.randint(0,11,size=(3,3))

In [98]:
# Compare the two arrays with '>'
r1>r2

array([[False,  True,  True],
       [ True, False, False],
       [False, False, False]])

What happens when you compare the arrays with `>`?

In [99]:
# Compare the two arrays with '>='
r1>=r2

array([[ True,  True,  True],
       [ True,  True,  True],
       [False, False, False]])

In [100]:
# Find which elements of the first array are greater than 7
r1>7

array([[False, False,  True],
       [False,  True, False],
       [False, False, False]])

In [101]:
# Which parts of each array are equal? (try using '==')
r1==r2

array([[ True, False, False],
       [False,  True,  True],
       [False, False, False]])

In [105]:
# Sort one of the arrays you just created in ascending order
np.argsort(r1)

array([[0, 1, 2],
       [2, 0, 1],
       [2, 0, 1]])

In [106]:
# Sort the indexes of one of the arrays you just created
np.argsort(r1, axis=None)

array([5, 0, 8, 6, 1, 7, 3, 2, 4])

In [114]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(r1)

np.int64(2)

In [113]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(r1)

np.int64(5)

In [112]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(r1, axis=1)

array([2, 1, 1])

In [111]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(r1, axis=0)

array([0, 0, 1])

In [115]:
# Create an array of normally distributed random numbers
np.random.randn(3, 5)

array([[ 0.7896728 ,  0.43148946, -1.0967523 , -0.68230156,  0.88751161],
       [ 0.60548313, -0.72029799, -0.26993377, -0.14346223,  0.61700378],
       [ 1.2489407 ,  0.06564916,  1.16920765,  0.87331697,  0.20565013]])

In [120]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.